### ISSUE TITLE
Isolate Core API

### ISSUE THREAD

**Issue by LesterCerioli** [LesterCerioli/Express-Store#7]
### This procedure permit isolate API reference other modules and it's possible to have an API UI Interface

**Comment by LesterCerioli** [comment]
Build ExpressStoreCore solution and move Projects to this new solution.
Remove ExpressStore Core project

**Comment by MadalenaDiasSec** [comment]
I think so we should keep Core microservice 'cause legacy has dependencies. When we finish to build Express Store Core we can remove its.
